AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront Distribution for SmartDeploy v6 Enhanced

Parameters:
  EC2PublicIP:
    Type: String
    Default: "98.83.207.85"
    Description: EC2 instance public IP

  AppPort:
    Type: String
    Default: "8506"
    Description: SmartDeploy application port

Resources:
  SmartDeployCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: SmartDeploy v6 Enhanced - CloudFormation Deployment Pipeline
        Enabled: true
        PriceClass: PriceClass_100  # Use only North America and Europe edge locations

        Origins:
          - Id: SmartDeployEC2Origin
            DomainName: !Sub "${EC2PublicIP}.nip.io"
            CustomOriginConfig:
              HTTPPort: !Ref AppPort
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
              OriginSSLProtocols:
                - TLSv1.2
                - TLSv1.3
              OriginReadTimeout: 60
              OriginKeepaliveTimeout: 5

        DefaultCacheBehavior:
          TargetOriginId: SmartDeployEC2Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true

          # Cache policy for dynamic content (Streamlit app)
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # CachingDisabled
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf  # CORS-S3Origin

          # Allow all headers and cookies to pass through (needed for Streamlit)
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
            Headers:
              - "*"

        # Custom error pages
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /
            ErrorCachingMinTTL: 0
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /
            ErrorCachingMinTTL: 0

        # Logging (optional)
        # Logging:
        #   Bucket: !Sub "${LoggingBucket}.s3.amazonaws.com"
        #   Prefix: cloudfront-logs/smartdeploy/

        # Geo restrictions (optional)
        Restrictions:
          GeoRestriction:
            RestrictionType: none

        ViewerCertificate:
          CloudFrontDefaultCertificate: true

        HttpVersion: http2
        DefaultRootObject: ""
        IPV6Enabled: true

      Tags:
        - Key: Name
          Value: SmartDeploy-CloudFront
        - Key: Application
          Value: SmartDeploy
        - Key: Environment
          Value: Production
        - Key: Version
          Value: v6-enhanced

Outputs:
  CloudFrontURL:
    Description: CloudFront Distribution URL for SmartDeploy
    Value: !Sub "https://${SmartDeployCloudFront.DomainName}"
    Export:
      Name: SmartDeploy-CloudFront-URL

  CloudFrontDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt SmartDeployCloudFront.DomainName
    Export:
      Name: SmartDeploy-CloudFront-Domain

  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref SmartDeployCloudFront
    Export:
      Name: SmartDeploy-CloudFront-DistributionId